"""Append bundled practice MCQs from stdin-style list in this script."""
from __future__ import annotations

import json
from pathlib import Path

QUESTIONS_PATH = Path("data/questions.json")
NEW = [
  {
    "id": "gate_ce_soil_01",
    "question": "For a given soil sample, the void ratio (e) can be:",
    "type": "mcq",
    "options": ["e = 0", "0 < e < 1", "e > 0", "e < 0"],
    "correct": 2,
    "solution": "Void ratio is the ratio of the volume of voids to the volume of solids. Since the volume of voids can be greater than the volume of solids, e can be greater than 1, but it must be strictly greater than 0.",
    "subject": "Soil Mechanics",
    "topic": "Properties of Soils",
    "marks": 1,
    "year": 2020,
    "difficulty": "Easy",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_fluid_02",
    "question": "Kinematic viscosity of a fluid is defined as the ratio of:",
    "type": "mcq",
    "options": [
      "Dynamic viscosity to density",
      "Density to dynamic viscosity",
      "Dynamic viscosity to pressure",
      "Pressure to dynamic viscosity",
    ],
    "correct": 0,
    "solution": "Kinematic viscosity is the ratio of dynamic viscosity (μ) to the density (ρ) of the fluid.",
    "subject": "Fluid Mechanics",
    "topic": "Fluid Properties",
    "marks": 1,
    "year": 2019,
    "difficulty": "Easy",
    "exam": "ESE",
    "paper": "P2",
  },
  {
    "id": "gate_ce_som_03",
    "question": "The relationship between modulus of elasticity (E), bulk modulus (K) and Poisson's ratio (μ) is:",
    "type": "mcq",
    "options": [
      "E = 3K(1 - 2μ)",
      "E = 2K(1 - 2μ)",
      "E = 3K(1 - μ)",
      "E = 2K(1 - μ)",
    ],
    "correct": 0,
    "solution": "The standard relationship between Elastic Modulus, Bulk Modulus, and Poisson's ratio is E = 3K(1 - 2μ).",
    "subject": "Strength of Materials",
    "topic": "Elastic Constants",
    "marks": 1,
    "year": 2021,
    "difficulty": "Medium",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_env_04",
    "question": "The standard BOD (Biochemical Oxygen Demand) is measured at:",
    "type": "mcq",
    "options": [
      "20°C for 3 days",
      "20°C for 5 days",
      "25°C for 3 days",
      "25°C for 5 days",
    ],
    "correct": 1,
    "solution": "The standard biochemical oxygen demand (BOD) test is conducted at a temperature of 20°C for a period of 5 days (BOD5).",
    "subject": "Environmental Engineering",
    "topic": "Waste Water Characteristics",
    "marks": 1,
    "year": 2018,
    "difficulty": "Easy",
    "exam": "ESE",
    "paper": "P2",
  },
  {
    "id": "gate_ce_trans_05",
    "question": "The stopping sight distance depends upon:",
    "type": "mcq",
    "options": [
      "Total reaction time of driver",
      "Speed of vehicle",
      "Efficiency of brakes",
      "All of the above",
    ],
    "correct": 3,
    "solution": "Stopping sight distance is the sum of lag distance and braking distance, which depend on driver's reaction time, initial speed, and braking efficiency respectively.",
    "subject": "Transportation Engineering",
    "topic": "Highway Geometric Design",
    "marks": 1,
    "year": 2022,
    "difficulty": "Easy",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_rcc_06",
    "question": "In IS 456:2000, what is the minimum grade of concrete for RCC in severe exposure conditions?",
    "type": "mcq",
    "options": ["M20", "M25", "M30", "M35"],
    "correct": 2,
    "solution": "According to IS 456:2000 Table 5, the minimum grade of concrete for reinforced concrete under severe exposure conditions is M30.",
    "subject": "RCC Design",
    "topic": "Concrete Technology",
    "marks": 2,
    "year": 2020,
    "difficulty": "Medium",
    "exam": "ESE",
    "paper": "P1",
  },
  {
    "id": "gate_ce_survey_07",
    "question": "If the magnetic bearing of a line is 48°24' and magnetic declination is 5°38' East, then the true bearing is:",
    "type": "mcq",
    "options": ["54°02'", "42°46'", "48°24'", "5°38'"],
    "correct": 0,
    "solution": "True Bearing = Magnetic Bearing + Eastern Declination = 48°24' + 5°38' = 54°02'.",
    "subject": "Surveying",
    "topic": "Compass Surveying",
    "marks": 2,
    "year": 2019,
    "difficulty": "Medium",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_hydro_08",
    "question": "Isohyets are the imaginary lines drawn on a map joining the points of equal:",
    "type": "mcq",
    "options": [
      "Atmospheric pressure",
      "Elevation",
      "Humidity",
      "Rainfall",
    ],
    "correct": 3,
    "solution": "An isohyet is a contour line drawn on a map connecting points that receive equal amounts of rainfall.",
    "subject": "Hydrology",
    "topic": "Precipitation",
    "marks": 1,
    "year": 2017,
    "difficulty": "Easy",
    "exam": "ESE",
    "paper": "P2",
  },
  {
    "id": "gate_ce_steel_09",
    "question": "The density of steel used in structural design is generally taken as:",
    "type": "mcq",
    "options": [
      "7850 kg/m³",
      "8000 kg/m³",
      "7500 kg/m³",
      "8500 kg/m³",
    ],
    "correct": 0,
    "solution": "According to IS 800:2007, the mass density of structural steel is taken as 7850 kg/m³.",
    "subject": "Steel Structures",
    "topic": "General Design Requirements",
    "marks": 1,
    "year": 2018,
    "difficulty": "Easy",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_fluid_10",
    "question": "Froude number is defined as the ratio of inertia force to:",
    "type": "mcq",
    "options": [
      "Viscous force",
      "Gravity force",
      "Surface tension force",
      "Elastic force",
    ],
    "correct": 1,
    "solution": "Froude number is a dimensionless number defined as the ratio of the flow inertia to the external field (the latter in many applications simply due to gravity).",
    "subject": "Fluid Mechanics & Hydraulics",
    "topic": "Dimensional Analysis",
    "marks": 1,
    "year": 2021,
    "difficulty": "Easy",
    "exam": "ESE",
    "paper": "P2",
  },
  {
    "id": "gate_ce_soil_11",
    "question": "The liquid limit of a soil is typically determined using:",
    "type": "mcq",
    "options": [
      "Pycnometer",
      "Casagrande's apparatus",
      "Hydrometer",
      "Proctor's compaction apparatus",
    ],
    "correct": 1,
    "solution": "Casagrande's liquid limit device is used to determine the liquid limit of soil in the laboratory.",
    "subject": "Soil Mechanics",
    "topic": "Index Properties",
    "marks": 1,
    "year": 2020,
    "difficulty": "Easy",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_irrigation_12",
    "question": "The relation between Duty (D) in hectares/cumec, Delta (Δ) in meters, and Base period (B) in days is:",
    "type": "mcq",
    "options": [
      "Δ = 8.64 B / D",
      "Δ = 8.64 D / B",
      "Δ = 8.64 B D",
      "Δ = 864 B / D",
    ],
    "correct": 0,
    "solution": "The fundamental relation is Δ = 8.64 B / D, where Δ is in meters, B is in days, and D is in ha/cumec.",
    "subject": "Irrigation Engineering",
    "topic": "Water Requirements of Crops",
    "marks": 1,
    "year": 2019,
    "difficulty": "Medium",
    "exam": "ESE",
    "paper": "P2",
  },
  {
    "id": "gate_ce_steel_13",
    "question": "The maximum slenderness ratio of a steel tension member in which a reversal of direct stress occurs due to loads other than wind or seismic forces is:",
    "type": "mcq",
    "options": ["180", "250", "300", "350"],
    "correct": 0,
    "solution": "As per IS 800, the maximum effective slenderness ratio for a tension member with reversal of direct stress due to loads other than wind/seismic is 180.",
    "subject": "Steel Structures",
    "topic": "Tension Members",
    "marks": 2,
    "year": 2021,
    "difficulty": "Hard",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_trans_14",
    "question": "Bitumen is completely soluble in:",
    "type": "mcq",
    "options": [
      "Carbon disulphide",
      "Water",
      "Acetic acid",
      "Ammonia",
    ],
    "correct": 0,
    "solution": "Bitumen is a hydrocarbon material which is completely soluble in carbon disulphide (CS2) and carbon tetrachloride (CCl4).",
    "subject": "Transportation Engineering",
    "topic": "Pavement Materials",
    "marks": 1,
    "year": 2018,
    "difficulty": "Easy",
    "exam": "ESE",
    "paper": "P1",
  },
  {
    "id": "gate_ce_env_15",
    "question": "Biochemical Oxygen Demand (BOD) of safe drinking water must be:",
    "type": "mcq",
    "options": ["0 mg/L", "5 mg/L", "10 mg/L", "20 mg/L"],
    "correct": 0,
    "solution": "Safe drinking water should be free of any organic biodegradable matter, hence its BOD must be strictly zero.",
    "subject": "Environmental Engineering",
    "topic": "Quality of Water",
    "marks": 1,
    "year": 2019,
    "difficulty": "Easy",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_rcc_16",
    "question": "The modulus of rupture of concrete gives:",
    "type": "mcq",
    "options": [
      "The direct tensile strength of the concrete",
      "The direct compressive strength of the concrete",
      "The tensile strength of the concrete under bending",
      "The characteristic strength of the concrete",
    ],
    "correct": 2,
    "solution": "Modulus of rupture is a measure of the tensile strength of concrete in bending (flexural tensile strength).",
    "subject": "RCC Design",
    "topic": "Properties of Concrete",
    "marks": 1,
    "year": 2020,
    "difficulty": "Medium",
    "exam": "ESE",
    "paper": "P1",
  },
  {
    "id": "gate_ce_cpm_17",
    "question": "In a PERT network, the expected time (te) of an activity is given by:",
    "type": "mcq",
    "options": [
      "(to + tm + tp) / 6",
      "(to + 4tm + tp) / 6",
      "(to + 2tm + tp) / 6",
      "(to + 4tm + tp) / 4",
    ],
    "correct": 1,
    "solution": "The expected time in PERT follows a Beta distribution and is calculated as te = (to + 4tm + tp) / 6, where to=optimistic, tm=most likely, tp=pessimistic time.",
    "subject": "Construction Materials and Management",
    "topic": "PERT and CPM",
    "marks": 2,
    "year": 2022,
    "difficulty": "Medium",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_som_18",
    "question": "The point of contraflexure is defined as the point where:",
    "type": "mcq",
    "options": [
      "Shear force changes sign",
      "Bending moment is maximum",
      "Bending moment changes sign",
      "Deflection is maximum",
    ],
    "correct": 2,
    "solution": "A point of contraflexure is a point on a beam where the bending moment changes its sign from positive to negative or vice-versa.",
    "subject": "Strength of Materials",
    "topic": "Bending Moment & Shear Force",
    "marks": 1,
    "year": 2021,
    "difficulty": "Easy",
    "exam": "ESE",
    "paper": "P1",
  },
  {
    "id": "gate_ce_trans_19",
    "question": "For water bound macadam (WBM) roads in localities of heavy rainfall, the recommended value of camber is:",
    "type": "mcq",
    "options": ["1 in 33", "1 in 40", "1 in 50", "1 in 60"],
    "correct": 0,
    "solution": "According to IRC guidelines, for WBM roads in heavy rainfall areas, the recommended camber is 1 in 33 (or 3.0%).",
    "subject": "Transportation Engineering",
    "topic": "Highway Cross Section Elements",
    "marks": 1,
    "year": 2020,
    "difficulty": "Medium",
    "exam": "GATE",
    "paper": None,
  },
  {
    "id": "ese_ce_survey_20",
    "question": "The 'Two Peg Test' is performed to check or adjust:",
    "type": "mcq",
    "options": [
      "Line of collimation",
      "Bubble tube axis",
      "Cross hairs",
      "Horizontal axis",
    ],
    "correct": 0,
    "solution": "The Two Peg Test is carried out to check whether the line of collimation of a level is parallel to the axis of the bubble tube.",
    "subject": "Surveying",
    "topic": "Levelling",
    "marks": 1,
    "year": 2019,
    "difficulty": "Medium",
    "exam": "ESE",
    "paper": "P1",
  },
]


def main() -> None:
    existing = json.loads(QUESTIONS_PATH.read_text(encoding="utf-8"))
    ids = {q.get("id") for q in existing}
    added = 0
    for q in NEW:
        if q["id"] in ids:
            continue
        existing.append(q)
        ids.add(q["id"])
        added += 1
    QUESTIONS_PATH.write_text(
        json.dumps(existing, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Added {added} questions ({len(existing)} total)")


if __name__ == "__main__":
    main()
